make:
	gcc  -shared -Wall -fPIC  -o grid_utils.so grid_utils.c -lm -lgsl -lgslcblas
	gcc  -shared -Wall -fPIC  -o integrand.so integrand.c -lm -lgsl -lgslcblas
	#gcc  -shared -Wall -fPIC  -o disk.so disk.c -lm -lgsl -lgslcblas
	#gcc -shared -fPIC -Wall -o functionlib.so functionlib.c -lm -lgsl -lgslcblas

#-shared -fPIC
