make:
	gcc -Wall -shared -fPIC -o compiled_functions_library.so compiled_functions_library.c -lm -lgsl -lgslcblas
	#gcc -shared -fPIC -Wall -o functionlib.so functionlib.c -lm -lgsl -lgslcblas

#-shared -fPIC
